services:
#  cpp-server:
#    build:
#      context: .
#      dockerfile: cpp-server/Dockerfile
#    volumes:
#      - ../data:/usr/src/netflix-project/build/data
#    container_name: netflix_cpp_server_container
#    working_dir: /usr/src/netflix-project/web-server/cpp-server

  nodejs-server:
    build:
      context: .
      dockerfile: nodejs-server/Dockerfile
    volumes:
      - ../data:/usr/src/netflix-project/build/data
    container_name: netflix_nodejs_server_container
    working_dir: /usr/src/netflix-project/web-server/nodejs-server
    depends_on:
      - mongo
    ports:
      - "19844:19844"

  python-client:
    build:
      context: ./cpp-server/python-client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    container_name: netflix_python_client_container
    working_dir: /usr/src/netflix-client/web-server/cpp-server/python-client

  cpp-tests:
    build:
      context: ./cpp-server
      dockerfile: Dockerfile.test
    container_name: netflix_cpp_tests
    working_dir: /usr/src/netflix-project/web-server/cpp-server
    command: ./runTests

  mongo:
    image: mongo:8
    container_name: mongo_container
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 

volumes:
  server_data: 
  web_data:    
  mongo_data:  
