services:
  cpp-server:
    build:
      context: .
      dockerfile: cpp-server/Dockerfile
    volumes:
      - ../data:/usr/src/netflix-project/build/data
    container_name: netflix_cpp_server_container
    working_dir: /usr/src/netflix-project/web-server/cpp-server
    restart: unless-stopped

  nodejs-server:
    build:
      context: .
      dockerfile: nodejs-server/Dockerfile
    volumes:
      - ../data:/usr/src/netflix-project/build/data
      - ./nodejs-server/uploads:/usr/src/netflix-project/web-server/nodejs-server/uploads
    container_name: netflix_nodejs_server_container
    working_dir: /usr/src/netflix-project/web-server/nodejs-server
    depends_on:
      - mongo
    ports:
      - "19844:19844"
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  server_data:
  web_data:
  mongo_data:
