services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true

    volumes:
      - .:/usr/src/netflix-project/data
    container_name: netflix_app
    working_dir: /usr/src/netflix-project/build
    command: ./NetflixProject

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test

    volumes:
      - .:/usr/src/netflix-project/data
    container_name: netflix_app_tests
    working_dir: /usr/src/netflix-project/build/tests
    command: ./runTests

