services:
  c-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ../data:/usr/src/netflix-project/build/data
    container_name: netflix_c_server_container
    working_dir: /usr/src/netflix-project/build

  web-server:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ../data:/usr/src/netflix-project/build/data
    container_name: netflix_web_server_container
    working_dir: /usr/src/netflix-project/web
    depends_on:
      - mongo
    ports:
      - "19844:19844"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    container_name: netflix_client_container
    working_dir: /usr/src/netflix-client

  tests:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    container_name: netflix_app_tests
    working_dir: /usr/src/netflix-project/build/tests
    command: ./runTests

  mongo:
    image: mongo:8
    container_name: mongo_container
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 

volumes:
  server_data: 
  web_data:    
  mongo_data:  