services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true

    working_dir: /usr/src/netflix-project/build
    command: ./NetflixProject

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test

    working_dir: /usr/src/netflix-project/build/tests
    command: ./runTests

