FROM gcc:latest

# Install required tools and libraries for tests
RUN apt-get update && apt-get install -y \
    cmake \
    libgtest-dev

# Compile and install GTest
RUN cd /usr/src/gtest && \
    cmake CMakeLists.txt && \
    make && \
    cp lib/*.a /usr/lib

# Copy project files
COPY . /usr/src/netflix-project
WORKDIR /usr/src/netflix-project

# Clean up unnecessary files
RUN rm -rf build CMakeCache.txt CMakeFiles cmake_install.cmake Makefile

# Create build directory
RUN mkdir build
WORKDIR /usr/src/netflix-project/build

# Build project with tests enabled
RUN cmake -DENABLE_TESTS=ON .. && make

CMD ["./runTests"]
